name: CI

on:
  push:
    paths:
    - '**.zig'
  pull_request:
    paths:
    - '**.zig'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Build
        run: zig build

      - name: Run Tests with filesystem
        run: zig build test -Din_memory=false

      - name: Run Tests in memory
        run: zig build test -Din_memory=true
